name: ci

on:
  push:
    branches-ignore:
      - gh-pages
      - "renovate/**"
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        node_version: [ '8','10','12','14','16','18' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "${{ matrix.node_version }}"

      - run: npm i

      - run: npm test
